//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seneha_Hanımın_Mutfağı
{
    using System;
    using System.Collections.Generic;
    
    public partial class corbalar
    {
        public int No { get; set; }
        public string Ürün_Ad { get; set; }
        public Nullable<decimal> Ürün_Fiyat { get; set; }
    }
}
