//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seneha_Hanımın_Mutfağı
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SenehaCafeEntities3 : DbContext
    {
        public SenehaCafeEntities3()
            : base("name=SenehaCafeEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anayemek> anayemeks { get; set; }
        public virtual DbSet<corbalar> corbalars { get; set; }
        public virtual DbSet<dondurma> dondurmas { get; set; }
        public virtual DbSet<icecekler> iceceklers { get; set; }
        public virtual DbSet<ödeme> ödeme { get; set; }
        public virtual DbSet<salata> salatas { get; set; }
        public virtual DbSet<sıcak_icecek> sıcak_icecek { get; set; }
        public virtual DbSet<siparisler> siparislers { get; set; }
        public virtual DbSet<soguk_icecek> soguk_iceceks { get; set; }
        public virtual DbSet<tatlılar> tatlılar { get; set; }
    }
}
