//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seneha_Hanımın_Mutfağı
{
    using System;
    using System.Collections.Generic;
    
    public partial class ödeme
    {
        public int ıd { get; set; }
        public string masa_no { get; set; }
        public Nullable<decimal> indirim { get; set; }
        public Nullable<decimal> kdv { get; set; }
        public Nullable<decimal> toplam { get; set; }
        public Nullable<decimal> ödenecek { get; set; }
    }
}
